# Generated by Django 4.2.1 on 2023-06-23 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.CharField(max_length=80, verbose_name='Descripción del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
                ('descuentoSubP', models.IntegerField(verbose_name='Descuento subscriptor')),
                ('descuentoSubO', models.IntegerField(verbose_name='Descuento oferta')),
                ('imagenProducto', models.ImageField(default='sinfoto.jpg', upload_to='img/', verbose_name='Imagen')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo de usuario')),
                ('rut', models.CharField(max_length=15, verbose_name='RUT')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('subscrito', models.BooleanField(verbose_name='Subscrito')),
                ('imagen', models.ImageField(upload_to='perfiles/', verbose_name='Imagen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'db_table': 'Perfil',
                'ordering': ['tipo_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('nro_boleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro boleta')),
                ('monto_sin_iva', models.IntegerField(verbose_name='Monto sin IVA')),
                ('iva', models.IntegerField(verbose_name='IVA')),
                ('total_a_pagar', models.IntegerField(verbose_name='Total a pagar')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de venta')),
                ('fecha_despacho', models.DateField(blank=True, null=True, verbose_name='Fecha de despacho')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('estado', models.CharField(choices=[('Anulado', 'Anulado'), ('Vendido', 'Vendido'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], max_length=50, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfil')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'Boleta',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idProductoBode', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProductoBode', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('stockProducto', models.IntegerField(verbose_name='Stock producto')),
                ('categoriaProductoBode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Nombre de la categoría')),
            ],
        ),
    ]
