# Generated by Django 4.2.1 on 2023-06-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.CharField(max_length=80, verbose_name='Descripción del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
                ('descuentoSubP', models.IntegerField(verbose_name='Descuento subscriptor')),
                ('descuentoSubO', models.IntegerField(verbose_name='Descuento oferta')),
                ('imagenProducto', models.ImageField(default='sinfoto.jpg', upload_to='img/', verbose_name='Imagen')),
                ('precio_con_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Nombre de la categoría')),
            ],
        ),
    ]
