# Generated by Django 4.2.1 on 2023-06-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_con_descuento',
        ),
    ]
