# Generated by Django 4.2.1 on 2023-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_precio_con_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto'),
        ),
    ]
