# Generated by Django 4.2.1 on 2023-06-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_idcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idProductoBode', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProductoBode', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('stockProducto', models.IntegerField(verbose_name='Stock producto')),
                ('categoriaProductoBode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Nombre de la categoría')),
            ],
        ),
    ]
